### ISSUE TITLE
Cannot use this with React

### ISSUE THREAD

**Issue by abhishekdhaduvai** [PredixDev/px-key-value-pair#2]
# Cannot use this with React

We cannot use this with React since the "key" attribute is reserved. Maybe change the attribute to something else?

The component in React looks like this:
<img width="431" alt="screen shot 2018-01-23 at 11 46 19 am" src="https://user-images.githubusercontent.com/17446357/35297184-1bfcd1d0-0033-11e8-8458-307d5121566a.png">

Expected:
![image](https://user-images.githubusercontent.com/17446357/35297234-3a544f0a-0033-11e8-9e56-e40e74fdfa5a.png)

**Comment by davidrleonard** [comment]
See also https://github.com/PredixDev/px-map/issues/120. I'll post the same answer here:

> We use key in other components in px-map and elsewhere to name properties that accept API keys. This would be a breaking change for this component and require breaking changes elsewhere. Key is not a reserved HTMLElement attribute or property in the web platform specs as far as I’m aware. We won’t be making this change.

> You can still use this component in React by finding its ref in the componentWillMount or componentWillRecieveProps and setting the key property directly.

You can see an example of using px-key-value-pair with React (and the `key` attribute) here: https://github.com/predixdesignsystem/px-sample-app-react/blob/7704afc06667812dc4cf9f34c514f3890a7089ba/src/views/DashboardView.js#L49

And the `KeyValuePair` React wrapper here: https://github.com/predixdesignsystem/px-sample-app-react/blob/7704afc06667812dc4cf9f34c514f3890a7089ba/src/web-components/KeyValuePair.js
